server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.194.128:3306/jigsaw?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null # JSON?????????
  data:
    redis:
      password: 123321
      host: 192.168.194.128
      port: 6379
mybatis-plus:
  type-aliases-package: com.xuexian.entity # ?????
logging:
  level:
    com.hmdp: debug
